repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
    -   id: pretty-format-json
        args: [--autofix, --indent=4]
    -   id: trailing-whitespace

-   repo: https://github.com/PyCQA/pylint
    rev: 'v2.9.5'
    hooks:
    -   id: pylint

-   repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
    -   id: isort

-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: 'v2.0.1'
    hooks:
    -   id: docker-compose-check

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
    -   id: add-trailing-comma

-   repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
    -   id: black
